name: Check Markdown links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@master
        with:
          config-file: '.github/linkcheck_config.json'
